services:
  db:
    image: postgres:16-alpine
    container_name: farms_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: farmsdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - farms_network

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: farms_app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: farmsdb
      DB_SYNCHRONIZE: true
      DB_LOGGING: true
      DB_LOG_LEVEL: debug
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    networks:
      - farms_network

volumes:
  db_data:
    driver: local

networks:
  farms_network:
    driver: bridge
